Fibo
stas0n7/ruby-lessons pull request #2
Opened 2019-08-10 12:50 UTC by stas0n7

2019-08-10 15:14 UTC, vrtsev requested changes
Проревьювил. Поправь код согласно комментариям и добавь все изменения новым коммитом с названием например 'Improve code according to code review'

2019-08-10 15:14 UTC, vrtsev commented on lesson2/fibonacci.rb
> +while fi[-1] < 100
гуд. на будущее полезный совет: последний элемент массива можно так же получить с помощью 
`fi.last`, первый элемент массива - с помощью `.first`, а ПРЕДпоследний можно получить с помощью [-2]

https://ruby-doc.org/core-2.6.1/Array.html#method-i-first

2019-08-10 15:14 UTC, vrtsev commented on lesson2/fibonacci.rb
> +    fi << fi[-1] + fi[-2]
Первый элемент массива можно так же получить с помощью `fi.first`

2019-08-10 15:14 UTC, vrtsev commented on lesson2/fibonacci.rb
> +    end
`end` должен быть без пробелов. Это называется 'индентация', загугли этот термин. Это важно для читаемости кода и для стилистики оформления. тоже важная штука

2019-08-10 15:15 UTC, vrtsev commented
В ПРе есть пустой закоммиченный файл `ta`. На будущее старайся в ПРы не добавлять ничего лишнего. ПР должен содержать только все самое необходимое  и  должен быть вылизан до идеала

2019-08-10 15:36 UTC, stas0n7 commented on lesson2/fibonacci.rb
> +    fi << fi[-1] + fi[-2]
ну я думаю тут fi.first не катит иначе задача будет решена неверно и будут бесконечные еденицы в массиве , разве нет ? нужно именно последнее с предпоследним складывать

2019-08-10 20:30 UTC, vrtsev commented on lesson2/fibonacci.rb
> +    fi << fi[-1] + fi[-2]
Да, тут большой плюс за внимательность. Не обратил внимание, что берем ПРЕДпоследний элемент

2019-08-13 15:25 UTC, vrtsev commented on lesson2/month.rb
> +month = { january: 31,
Хэши оформляются таким образом:
```
month = {
  january: 31,
  february: 28,
 ...
}
```

В твоем решении тебе пришлось каждое ключ знание выравнивать и делать кучу пробелов. Это лишнее. После открытия фигурной скобки просто начинай писать ключ-значение на новой строке

2019-08-13 15:31 UTC, vrtsev requested changes
Поревьювил последнее решение
Нету никаких критических замечаний

Не забудь так же в файле `fibonacci.rb` переделать все по оставленному комментарию и потом обновить его в этом ПРе

2019-08-13 21:14 UTC, stas0n7 commented on lesson2/month.rb
> +month = { january: 31,
исправил

2019-08-13 21:21 UTC, stas0n7 commented on lesson2/fibonacci.rb
> +    end
убрал пробелы на днях

2019-08-13 21:25 UTC, stas0n7 commented
А что конкретно по фибоначи нужно сделать ? я вроде пробелы убрал перед end и закомитил на днях.

2019-08-13 21:25 UTC, vrtsev commented
> > Поревьювил последнее решение
> > Нету никаких критических замечаний
> > Не забудь так же в файле `fibonacci.rb` переделать все по оставленному комментарию и потом обновить его в этом ПРе
> > Ок. А что мне нужно переделать в фибоначи ? если ты про пробелы перед end я пофиксил вроде и закомитил это на днях

в этом файле я оставлял комментарий про `.last` и `.first`. Попробуй заменить `[-1]` и прочие элементы этими методами, НО там где берешь ПРЕДПОСЛЕДНИЙ элемент - оставь [-2], так как предпоследний элемент можно получить только таким образом

2019-08-13 21:27 UTC, vrtsev commented on lesson2/month.rb
> +month = { january: 31,
небольшой полезный хинт, вместо комментариев 'исправил' можешь нажимать на кнопку Resolve conversation

2019-08-15 18:33 UTC, vrtsev requested changes
Чекнул. Поправь код согласно моим комментариям
В целом отлично, нету критических замечаний. Keep it up :muscle:

2019-08-15 18:33 UTC, vrtsev commented on lesson2/task5.rb
> +#Заданы три числа, которые обозначают число, месяц, год. Найти порядковый номер даты, начиная отсчет с начала года.
Хорошей практикой является ВООБЩЕ не использовать русский язык в файлах с кодом
Во первых - Руссккий текст не совместим с некоторыми инструментами, которые вы будете использовать в будущем, будет вываливатся ошибка о том, что инструмент не может прочитать код с файла
Во вторых - это стандарт, что все должно быть на английском языке, так как в основном все заказчики - зарубежные и некоторые точно так же читают код, кто имеет технический бекграунд

По-этому лучше заранее приучаться писать все на английском языке. Это тебе будет только плюс

2019-08-15 18:33 UTC, vrtsev commented on lesson2/task5.rb
> +date = gets.to_i
небольшая подсказка: день на англ. будет `day`.
`date` - переводится как `дата`

Не критично, просто поправь. Хинт на будущее:
Казалось бы тут это мелочь, но в более сложных ситуациях неправильно именованная переменная, которая не правильно отражает смысл для чего она создана - только введет в заблуждение других товарищей в команде разработки и тебя, когда вернешься к коду спустя неск. месяцев

2019-08-15 18:33 UTC, vrtsev commented on lesson2/task5.rb
> +number_month = gets.to_i
Я думаю было бы лучше назвать переменную просто `month`. Просто следуя твоей логике `date` и `year` это тоже day_number И year_number :)

2019-08-15 18:33 UTC, vrtsev commented on lesson2/task5.rb
> +year = gets
А почему и на этом `gets` не вызвал сразу `.to_i` ?

2019-08-15 18:33 UTC, vrtsev commented on lesson2/task5.rb
> +  year = :leap
Вот в этом месте ты перезаписываешь переменную `year`, которая до этой строчки была `year = gets **.to_i**`.
Но это не самая лучшая практика и вот почему: Представь, что после всего кода в этом файле тебе придется написать еще какой-нибудь код (продолжение), в котором тебе нужно будет как-то получить изначальное значение, которое ввел пользователь. А ты его не получишь, потому что ты изначальное значение пользователя перезаписал на `year = :leap`

По смыслу, то, что ты записываешь в этом месте - это не год, это скорее тип года, следовательно можно назвать переменную, например `year_type` и записать в нее символ, в то время, как в переменной `year` просто можно сохранить то, что ввел юзер

2019-08-15 18:33 UTC, vrtsev commented on lesson2/task5.rb
> +  year = :not_leap
Тут точно так же не забудь переменную назвать `year_type`

2019-08-15 18:33 UTC, vrtsev commented on lesson2/task5.rb
> +days = 0
Обычно переменные, которые содержат в себе какое-то количество чего-либо принято называть `*_count`. Например `days_count = 0`

Но к примеру следующую строку `i = 0` не нужно так переименовывать, так как это индекс, и тут не уместо будет по смыслу использовать название `количество индексов, т.е. i_count`. Так что строка 19 правильная, хотя лично я бы назвал ее `index` для большей понятности

2019-08-15 18:33 UTC, vrtsev commented on lesson2/task5.rb
> +  months = [31, 29, 31, 30, 31, 30, 31, 30, 30, 31, 29, 31]
На строчках 11 и 15 не очень корректно прописывать новые массивы месяцев. Ты посути копируешь ПОЧТИ все в массиве, а это не гуд, можно упростить и все облегчить:

Как бы сделал я:
В начале файла определил бы переменную `all_months` и взял бы хэш с пред. твоего файла:
```
all_months = {
  january: 31,
  february: 28,
  march: 31,
  april: 30,
  may: 31,
  june: 30,
  july: 31,
  august: 30,
  september: 30,
  october: 31,
  november: 29,
  december: 31,
}
```

И потом на строке 11 (если год высокосный) просто сделал бы подмену значения `february` на `29` :
```
  all_months[:february] = 29
```
а строчку 15 вообще удалил бы, потому что если год не высокосный - то тогда в хэше ничего менять не надо, можно просто оставить

```
  year_type = :not_leap
  puts "Specified year is " + year_type.to_s
```
п.с. да, символы можно тоже конвертировать в строку и потом обьединить (приплюсовать две строки)
либо более продвинутый вариант использовать `интерполяцию`: `puts "Specified year is #{year_type}` - в этом случае символ сам переобразуется в строку

2019-08-15 18:33 UTC, vrtsev commented on lesson2/task5.rb
> +count = days - months[i - 1]
тут по смыслу более уместно назвать переменную `day_of_year`

2019-08-15 21:35 UTC, stas0n7 commented on lesson2/task5.rb
> +date = gets.to_i
day и date я знаю тут наверно получаеться наоборот, переменная правильно ,а  'puts' я не верно указал т.к не день недели запрашивать нужно , а как раз число. Я тогда 'puts' переделаю лучше )

2019-08-15 21:36 UTC, stas0n7 commented on lesson2/task5.rb
> +#Заданы три числа, которые обозначают число, месяц, год. Найти порядковый номер даты, начиная отсчет с начала года.
ок я постараюсь без русского и уберу первую строку

2019-08-15 21:38 UTC, vrtsev commented on lesson2/task5.rb
> +#Заданы три числа, которые обозначают число, месяц, год. Найти порядковый номер даты, начиная отсчет с начала года.
> уберу первую строку

Если имеешь ввиду убрать первую закоментированную строку - то можешь просто оставить, просто переведи ее на английский язык

2019-08-15 21:41 UTC, vrtsev commented on lesson2/task5.rb
> +date = gets.to_i
Та в принципе и день недели и число - они ж называются одинаково - `day`

Можешь даже загуглить `day month year` - увидишь, что такая связка правильная и число в дате так же называется `day`

2019-08-15 23:15 UTC, stas0n7 commented on lesson2/task5.rb
> +  months = [31, 29, 31, 30, 31, 30, 31, 30, 30, 31, 29, 31]
Так может я тоже самое сделаю ,но с массивом же? В начале сделаю переменную а на 11 строке подмену напишу all_months[1] = 29  . Ведь если заменить массив на хэш то это решение не будет работать разве нет ? А как подобное высчитать с хэшем я пока что хз.

2019-08-16 11:29 UTC, stas0n7 commented on lesson2/task5.rb
> +  year = :leap
аа тут кстати year = leap вообще получилась бесполезная переменная я её вообще уберу)

2019-08-16 11:29 UTC, stas0n7 commented on lesson2/task5.rb
> +  year = :not_leap
вообще уберу её

2019-08-16 11:51 UTC, stas0n7 commented
Ну я вроде бы ничего не забыл , только хэш не стал ставить а вывел массив в начало и удалил второй лишний. + удалил лишнюю переменную year = leap , year = is not leap , т.к понял что она лишняя и не делает ничего. Ну вообщем глянь )

2019-09-05 22:32 UTC, vrtsev requested changes
Проревьювил purchases. Поправь код согласно комменту

2019-09-05 22:32 UTC, vrtsev commented on lesson2/purchases.rb
> +  if name == "stop" || name == "стоп"
Тут не очень приколько спрашивать у юзера название товара и при этом вводить 'стоп'.
Во первых, еще не глядя на код я запустил код и у меня был бесконечный цикл и я не знал как его остановить.
По-этому, нужно перед циклом добавить какое-то предупреждение юзеру о том, что вообще будет происходить. Например `puts 'Please, populate products collection'`
Во вторых, просить название товара и при этом разрешать стопнуть цикл - тоже не есть гуд. Если ты просишь дать название товару, то значит нужно принимать ТОЛЬКО название товара.
По-этому, добавь после 12ой строки перед концом цикла вопрос юзеру, хочет ли он добавить еще товар. И если да, то продолжай цикл, а если нет, то выходи из него

2019-09-05 22:53 UTC, vrtsev commented
Есть замечание на счет именования коммита `redid 50% of task , i dont how correct wroting commit in this situation`. Тут можно просто назвать 'Improved %file_name% according to code-review comments'. Название ты уже изменить не сможешь по-этому просто на будущее пиши название в таком духе как я написал

2019-09-06 11:35 UTC, stas0n7 commented on lesson2/purchases.rb
> +  if name == "stop" || name == "стоп"
Всё поправил. На счёт бесконечного цикла вообще не понятно , т.к. у меня всё работает отлично.

2019-09-07 22:03 UTC, vrtsev commented on lesson2/purchases.rb
> +  if name == "stop" || name == "стоп"
Насчет бесконечного цикла я имел ввиду то, что так можно добавлять товары бесконечно. И когда-нибудь юзер заполнит нужное кол-во товаров и захочет остановится, но он не знает как, потому что пользователи сайта не будут иметь доступа к твоему коду и более того не будут в нем разбираться чтоб узнать когда именно нужно ввести стоп (точнее на каком моменте) да и вообще пользователи - не программисты :)

2019-09-07 22:53 UTC, vrtsev commented on lesson2/task5.rb
> +  months = [31, 29, 31, 30, 31, 30, 31, 30, 30, 31, 29, 31]
Вот так с хэшем
```
months_days = {
  january: 31,
  february: 28,
  march: 31,
  april: 30,
  may: 31,
  june: 30,
  july: 31,
  august: 30,
  september: 30,
  october: 31,
  november: 29,
  december: 31
}

puts "Type a day"
day = gets.to_i

puts "Type number of month"
month = gets.to_i

puts "type year"
year = gets.to_i

months = [31, 28, 31, 30, 31, 30, 31, 30, 30, 31, 29, 31]
if year % 4 == 0
  months_days[:february] = 29
  puts "leap year"
else
  puts "year is not leap"
end

days_count = 0

months_days.keys.each_with_index do |month_name, index|
  break if index >= month - 1
  days_count += months_days[month_name]
end

puts "#{days_count + day} day"
```

2019-09-07 22:54 UTC, vrtsev commented on lesson2/task5.rb
> +  months = [31, 29, 31, 30, 31, 30, 31, 30, 30, 31, 29, 31]
each_with_index автоматически в блок сам подставит тебе вторым аргументом индекс, даже переменную не надо обьявлять :)

2019-09-07 23:09 UTC, vrtsev requested changes

2019-09-07 23:09 UTC, vrtsev commented on lesson2/purchases.rb
> +purchases = Hash.new
А теперь улучшим код до идеала: 
Твоя задача была: наполнить коллекцию товаров. Коллекция - это почти всегда означает, что надо создать массив. Массив с товарами. А товаром может быть хэш с данными. Например
```
purchases = []

purchases << { name: name, price: price, quantity: quantity }
```

Потом когда будешь делать рассчеты:
```
purchases.each do |product|
  sum = product[:price] * product[:quantity]
  total += sum
  puts "#{product[:name]} - #{sum}" 
end
```

По идее код должен быть намного лаконичнее и читабельнее. Lets go

2019-09-07 23:09 UTC, vrtsev commented on lesson2/purchases.rb
> +purchases = Hash.new
Воспринимай хеши своего рода как класс. Класс содержит какие-то методы для работы с аттрибутами, а хэш - это как класс, у которого есть только аттрибуты (свойства) и все, например product = { свойство: значение, свойство2: значение }. И в этом примере товар - это своего рода обьект, у которого есть аттрибуты (название, цена, кол-во)

2019-09-07 23:09 UTC, vrtsev commented on lesson2/arr.rb
> +puts arr
Добавь в конце файла пустую строку. У тебя даже значек красный сигнализирует об этом после `puts arr`. В конце каждого файла должна быть ТОЛЬКО ОДНА пустая строка. Это такая конвенция есть

2019-09-07 23:09 UTC, vrtsev commented on lesson2/arr.rb
> +puts arr
Проследи, чтобы в каждом файле это было соблюдено

2019-09-07 23:35 UTC, vrtsev commented on lesson2/task5.rb
> +  months = [31, 29, 31, 30, 31, 30, 31, 30, 30, 31, 29, 31]
Посмотри мой кусок кода который я написал в комменте, разберись что к чему, потом закрой мой код и постарайся сам написать, следуя моей логике. Это чтоб отложилось в голове, ибо копипастить уже готовое - плохая практика

2020-02-18 22:01 UTC, merged